baseurl: "https://www.ready4-dev.com"
title: ready4-dev
author: Orygen
copyright: Copyright © 2022, Orygen.
paginate: 10
theme: hugo-clarity
disqusShortname: ''
DefaultContentLanguage: en
taxonomies:
  category: categories
  series: series
  tag: tags
markup:
  goldmark:
    extensions:
      typographer: no
    renderer:
      hardWraps: no
      unsafe: yes
      xhtml: no
  highlight:
    codeFences: yes
    guessSyntax: yes
    hl_Lines: --
    lineNoStart: 1
    lineNos: yes
    lineNumbersInTable: no
    noClasses: no
    tabWidth: 2
params:
  author: ready4-dev
  centerLogo: no
  codeLineNumbers: no
  codeMaxLines: 7
  enableMathNotation: no
  enforceLightMode: no
  fallBackOgImage: logos/logo.png
  figurePositionLabel: Figure
  figurePositionShow: no
  ga_analytics: XXXXXXXXXX
  introDescription: Documenting the development of an open souce youth mental health systems model.
  languageMenuName: "\U0001F310"
  largeTwitterCard: no
  logo: "logos/logo.png"
  mainSections: post
  mobileNavigation: left
  numberOfTagsShown: 14
  twitter: '@orygen_aus'
