title = "ready4 Open Science Mental Health"
baseURL = "https://ready4-dev.github.io/ready4/index.html"
languageCode = "en-US"
theme = "health-science-journal"

# The site's parameters
[params]
  home = "Home"
  abbreviatedTitle = "Health Sci. J. Theme"
  description = "The Health Sciences Journal Theme is a Hugo port of a theme developed by the Public Knowledge Project for Open Journal Systems. It is adapted under a GPL license."
  favicon = "img/favicon.png"
  mirrorfor = ""
  eISSN = ""
  printISSN = ""

  
  ## Publisher Information
  publisher = {name = "Orygen", city = "Melbourne", state = "Victoria", country = "Australia"}
  #journalDOI = "10.xxxx/demo"
  publisherjournalabbreviation = "Orygen"
  subjects = ["Subject1", "Subject2"]
  crossmark_enabled = false
  
  ## Homepage image. Different sizes can be used to provide responsiveness.
  homepageimageset = [{img = "img/homepage_480w.jpg", width = "480w", maxwidth = "800px"},
    {img = "img/homepage_960w.jpg", width = "960w", maxwidth = "1440px"},
    {img = "img/homepage_1920w.jpg", width = "1920w", maxwidth = ""}]
  homepageimagefallback = "img/homepage_960w.jpg"
  homepageimagealt = "Neurons artwork homepage image. CC0 Geralt/Pixabay id-582054"
  
  lenslogo = "img/lens-journal-logo.png"
  
  ## Set current issue or leave blank and the most recent issue will be used.
  currentissuepath = ""
  
  twittercard = "summary_large_image"
  twitterhandle = "@epistemehealth"
  socialimage = "img/twittercard.jpg"
  socialimagealt = "Health Sciences Journal Logo"
  socialdescription = "Health Sciences Journal Description"
  
  ## Set to true to load libraries from Cloudflare and Bootstrap CDNs where available. Otherwise leave blank.
  useCDN = false
  
  ## Custom blocks for the footer
  customblocks = [{name = "Github", content = "All our code is available on [GitHub](https://github.com/ready4-dev)"},
  {name = "Dataverse", content = "Replication data for our projects is available on our [Dataverse](https://dataverse.harvard.edu/dataverse/ready4)."},
  {name = "Contact Us", content = "For more information on this project contact [Matthew Hamilton](https://orcid.org/0000-0001-7407-9194), at [Orygen](https://www.orygen.org.au/)."}]
  
  footercontent = ""
  
  
  [privacy]
  [privacy.googleAnalytics]
    disable = true
  [privacy.disqus]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
  
  [menu]

    [[menu.main]]
      weight = 2
      name = "Articles"
      url = "current"
    [[menu.main]]
      weight = 3
      name = "Code"
      hasChildren = true
    [[menu.main]]
      parent = "Code"
      name = "Developer tools"
      url = "code/developer"
      weight = 4
    [[menu.main]]
      parent = "Code"
      name = "Modelling tools"
      url = "code/modelling"
      weight = 5
    [[menu.main]]
      parent = "Code"
      name = "Prediction tools"
      url = "code/prediction"
      weight = 6
    [[menu.main]]
      weight = 7
      name = "Data"
      url = "about/data"
    [[menu.main]]
      weight = 8
      name = "About"
      hasChildren = true
    [[menu.main]]
      parent = "About"
      name = "About ready4"
      url = "about/ready4"
      weight = 9
    [[menu.main]]
      parent = "About"
      name = "Contact"
      url = "contact"
      weight = 10

# Output formats
[mediaTypes]
  [mediaTypes."text/ris"]
    suffixes = ["ris"]
  [mediaTypes."text/bib"]
    suffixes = ["bib"]
  [mediaTypes."text/enw"]
    suffixes = ["enw"]
  [mediaTypes."text/latex"]
    suffixes = ["tex"]
    
[outputFormats]
  [outputFormats.galleyPDF]
    baseName = "view-pdf"
    isPlainText = true
    mediaType = "text/html"
    path = ""
  [outputFormats.galleyXML]
    baseName = "view-lens"
    isPlainText = true
    mediaType = "text/html"
    path = ""
  [outputFormats.galleyHTML]
    baseName = "view-html"
    isPlainText = true
    mediaType = "text/html"
    path = ""
  [outputFormats.customlens]
    baseName = "js/customlens"
    isPlainText = true
    mediaType = "application/javascript"
    path = ""
  [outputFormats.localfonts]
    baseName = "css/localfonts"
    isPlainText = true
    mediaType = "text/css"
    path = ""
  [outputFormats.lensfonts]
    baseName = "css/lensfonts"
    isPlainText = true
    mediaType = "text/css"
    path = ""
  [outputFormats.htmlgalleyfonts]
    baseName = "css/htmlgalleyfonts"
    isPlainText = true
    mediaType = "text/css"
    path = ""
  [outputFormats.exportris]
    baseName = "export-citation"
    isPlainText = true
    mediaType = "text/ris"
    path = ""
  [outputFormats.exportbib]
    baseName = "export-citation"
    isPlainText = true
    mediaType = "text/bib"
    path = ""
  [outputFormats.exportenw]
    baseName = "export-citation"
    isPlainText = true
    mediaType = "text/enw"
    path = ""
  [outputFormats.exportcsljson]
    baseName = "export-citation"
    isPlainText = true
    mediaType = "application/json"
    path = ""

[outputs]
  home = ["HTML", "customlens", "localfonts", "lensfonts", "htmlgalleyfonts"]
  page = ["html", "galleyPDF", "galleyXML", "galleyHTML", "exportris", "exportenw", "exportbib", "exportcsljson" ]

[taxonomies]
  keyword = "keywords"
