[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.101.0"
  HUGO_BUILDFUTURE = "true"

[context.deploy-preview.environment]
  command = "hugo --baseURL $DEPLOY_PRIME_URL"
  
[[redirects]]
from = "/docs/contribution-guidelines/*"
to = "https://readyforwhatsnext.org/docs/contribution-guidelines/:splat"
status = 301
force = true

[[redirects]]
from = "/docs/software/executables/programs/"
to = "https://readyforwhatsnext.org/docs/model/analyses/find/"
status = 301
force = true

[[redirects]]
from = "/docs/software/executables/subroutines/"
to = "https://readyforwhatsnext.org/docs/model/reporting/"
status = 301
force = true
 
[[redirects]]
from = "/docs/software/libraries/types/module/"
to = "https://readyforwhatsnext.org/docs/model/modules/finding/libraries/"
status = 301
force = true
 
[[redirects]]
from = "/docs/software/user-interfaces/"
to = "https://readyforwhatsnext.org/docs/model/decision-aids/"
status = 301
force = true
 
[[redirects]]
from = "/docs/model"
to = "https://readyforwhatsnext.org/docs/model/"
status = 301
force = true

[[redirects]]
from = "/docs/model/analyses/"
to = "https://readyforwhatsnext.org/docs/model/analyses/"
status = 301
force = true
 
[[redirects]]
from = "/docs/model/analyses/decision-aids/*"
to = "https://readyforwhatsnext.org/docs/model/decision-aids/:splat"
status = 301
force = true
 
[[redirects]]
from = "/docs/model/analyses/replication-code/*"
to = "https://readyforwhatsnext.org/docs/model/analyses/replication-code/:splat"
status = 301
force = true
 
[[redirects]]
from = "/docs/model/analyses/reporting-templates/"
to = "https://readyforwhatsnext.org/docs/model/reporting/"
status = 301
force = true
 
[[redirects]]
from = "/docs/model/datasets/*"
to = "https://readyforwhatsnext.org/docs/model/datasets/:splat"
status = 301
force = true
 
[[redirects]]
from = "/docs/model/modules/finding-modules/"
to = "https://readyforwhatsnext.org/docs/model/modules/finding/individual/"
status = 301
force = true
 
[[redirects]]
from = "/docs/model/modules/*"
to = "https://readyforwhatsnext.org/docs/model/modules/:splat"
status = 301
force = true
