[[main]]
  name = "Home"
  url = ""
  weight = -130
[[main]]
  name = "About"
  identifier = "About"
  #url = "about/"
  weight = -125
[[main]]
  parent = "About"
  name = "About ready4-dev"
  url = "about/"
  weight = -124
[[main]]
  parent = "About"
  name = "Motivation"
  url = "motivation/"
  weight = -123
[[main]]
  parent = "About"
  name = "Team"
  url = "team/"
  weight = -122
[[main]]
  parent = "About"
  name = "Contribute"
  url = "contribute/"
  weight = -121
[[main]]
  name = "Framework"
  url = "project/a_ready4-project/foundation/"#"framework/"
  weight = -115 
[[main]]
  name = "Models"
  url = "categories/models/"
  weight = -110
[[main]]
  parent = "Models"
  name = "Spring To Life - a model of people"
  url = "project/c_springtolife-project/"
  weight = -108
[[main]]
  parent = "Models"
  name = "Springtides - a model of places"
  url = "project/b_springtides-project/"
  weight = -107
[[main]]
  parent = "Models"
  name = "First Bounce - a model of platforms"
  url = "project/e_firstbounce-project/"
  weight = -106
[[main]]
  parent = "Models"
  name = "On Target - a model of programs"
  url = "project/d_ontarget-project/"
  weight = -106
[[main]]
  parent = "Models"
  name = "readyforwhatsnext - a systems model of people, places, platforms and programs"
  url = "project/f_readyforwhatsnext-project/"#"readyforwhatsnext/"
  weight = -104 
# Submenus are done this way: parent -> identifier
[[main]]
  name = "Datasets"
  identifier = "Datasets"
  #url = "toolkits/"
  weight = -101
[[main]]
  parent = "Datasets"
  name = "Datasets (Overview)"
  url = "publications_ov/datasets/"
  weight = -99
[[main]]
  parent = "Datasets"
  name = "Model Datasets"
  url = "publications/datasets/model/"
  weight = -98
[[main]]
  parent = "Datasets"
  name = "Instructional Datasets"
  url = "publications/datasets/instructional/"
  weight = -97
[[main]]
  identifier = "Software"
  name = "Software"
  weight = -90
[[main]]
  parent = "Software"
  name = "Software (Overview)"
  url = "publications_ov/software/"
  weight = -89
[[main]]
  parent = "Software"
  name = "Libraries"
  url = "publications/libraries/"
  weight = -88
[[main]]
  parent = "Software"
  name = "Programs"
  url = "publications/programs/"
  weight = -87
[[main]]
  parent = "Software"
  name = "Sub-Routines"
  url = "publications/subroutines/"
  weight = -87
[[main]]
  identifier = "Reports"
  name = "Reports"
  weight = -80
[[main]]
  parent = "Reports"
  name = "Reports (Overview)"#
  url = "publications_ov/reports/"#"insights/"#
  weight = -79
[[main]]
  parent = "Reports"
  name = "Scientific"#publications/reports/
  url = "publications/reports/scientific/"#"insights/"#
  weight = -78
[[main]]
  parent = "Reports"
  name = "Policy"#publications/reports/
  url = "publications/reports/policy/"#"insights/"#
  weight = -78
[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/ready4-dev"
