[[main]]
  name = "Home"
  url = ""
  weight = -110

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Toolkits"
  identifier = "Toolkits"
  #url = "toolkits/"
  weight = -100
[[main]]
  parent = "Toolkits"
  name = "About ready4 toolkits"
  url = "toolkits/"
  weight = -98
[[main]]
  parent = "Toolkits"
  name = "Authoring toolkits"
  url = "tags/authoring-toolkits/"
  weight = -96
[[main]]
  parent = "Toolkits"
  name = "Description toolkits"
  url = "tags/description-toolkits/"
  weight = -95
[[main]]
  parent = "Toolkits"
  name = "Modelling toolkits"
  url = "tags/modelling-toolkits/"
  weight = -94
[[main]]
  parent = "Toolkits"
  name = "Prediction toolkits"
  url = "tags/prediction-toolkits/"
  weight = -92
[[main]]
  identifier = "Datasets"
  name = "Datasets"
  url = "data/"
  weight = -90
[[main]]
  parent = "Datasets"
  name = "About ready4 datasets"
  url = "data/"
  weight = -88
[[main]]
  parent = "Datasets"
  name = "Package datasets"
  url = "tags/package-datasets/"
  weight = -86
[[main]]
  parent = "Datasets"
  name = "Dataverses"
  url = "tags/dataverses"
  weight = -84
[[main]]
  name = "Application"
  identifier = "Application"
  weight = -80
[[main]]
  parent = "Application"
  name = "Projects"
  url = "tags/project-descriptions/"
  weight = -78
[[main]]
  parent = "Application"
  name = "Insights"
  url = "tags/insights/"
  weight = -76
[[main]]
  name = "About"
  identifier = "About"
  url = "about/"
  weight = -70
[[main]]
  parent = "About"
  name = "About ready4"
  url = "about/"
  weight = -68 
[[main]]
  parent = "About"
  name = "ready4 purpose"
  url = "purpose/"
  weight = -66  
[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/ready4-dev"
